version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nextune-backend
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    restart: unless-stopped

  client:
    build:
      context: ./client-nextjs
      dockerfile: Dockerfile
    container_name: nextune-frontend-nextjs
    ports:
      - "3000:3000"
    env_file:
      - ./client-nextjs/.env.production
    depends_on:
      - server
    restart: unless-stopped

