# Stage 1: Build
FROM node:18 AS builder

WORKDIR /app

# Install dependencies based on the package.json and package-lock.json
COPY package*.json ./
RUN npm ci

# Copy all files and build
COPY . .
RUN npm run build

# Stage 2: Production image
FROM node:18-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
# Only copy necessary files for running the app
COPY --from=builder /app/package*.json ./
RUN npm ci --only=production

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

EXPOSE 3000
CMD ["npm", "start"]
