FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

ARG NODE_ENV=development
ENV NODE_ENV=$NODE_ENV

# Fallback to "dev" if NODE_ENV is not "production"
CMD if [ "$NODE_ENV" = "production" ]; then npm run build && npm run start; else npm run dev; fi
